import os

CARTOGRAM_DATA_DIR = os.environ['CARTOGRAM_DATA_DIR']
CARTOGRAM_COLOR = os.environ['CARTOGRAM_COLOR']
DEBUG = True if os.environ['CARTOGRAM_DEBUG'].lower() == "true" else False
DATABASE_URI = os.environ['CARTOGRAM_DATABASE_URI']

HOST = os.environ['CARTOGRAM_HOST']
PORT = int(os.environ['CARTOGRAM_PORT'])

SMTP_HOST = os.environ['CARTOGRAM_SMTP_HOST']
SMTP_PORT = int(os.environ['CARTOGRAM_SMTP_PORT'])
SMTP_AUTHENTICATION_REQUIRED = True if os.environ['CARTOGRAM_SMTP_AUTHENTICATION_REQUIRED'].lower() == "true" else False
SMTP_USER = os.environ['CARTOGRAM_SMTP_USER']
SMTP_PASSWORD = os.environ['CARTOGRAM_SMTP_PASSWORD']
SMTP_FROM_EMAIL = os.environ['CARTOGRAM_SMTP_FROM_EMAIL']
SMTP_DESTINATION = os.environ['CARTOGRAM_SMTP_DESTINATION']